%% Titles for the csv output from Holo Batch called 'ALL'

% This program takes as an input a csv file which is an output from the
% software Holo Batch called 'ALL'. This csv file generated by Holo Batch
% misses the name of the variables and their units at the top of each
% column. This program modifies this csv file and add two rows at the top
% of the file, containing the name of the variables and their units.

% For this program to work, the hard drive lexplore_hd must be
% connected to the computer. Before running the program, make sure that the 
% path to access the hard drive is the right one (K: or D: depending on the 
% computer).
% This progran should then be directly run, without modifications. A window 
% will open so that the user selects the csv file to be modified.

% Armelle BOUHALI, 30.09.2024


%% Workspace initialization

close all;                                                                 % close all figure
clear;                                                                     % remove all variables from the current workspace
clc;                                                                       % delete the command window


%% Selection and reading of the "ALL" csv file

% User selection of the 'ALL' csv file to be modified
[file,location] = uigetfile('*All.csv',...
    'Select a "ALL" csv file create by Holo Batch',...
    fullfile(extractBefore(pwd,'\00_Programs'),'03_Processed data'));      % user selects the 'ALL' csv file to which variable names and units will be added

if isequal(file,0)                                                         % a message is diplayed showing the selection made by the user
   disp('User selected Cancel');
else
   disp(['User selected ', fullfile(location,file)]);
end

% Reading of the selected csv file
ALL = readtable(fullfile(location,file));                                  % read the csv file selected and save it as a table


%% Creation of the columns'titles for the csv (variables names and units)

variables = ["Year (YYYY)", "Month (MM)","Day (DD)","Hour (HH)",...
    "Minute (MM)","Second (SS)","1/100s of a second (hhh)","Depth",...
    "Temperature","Input Voltage","Exposure","Laser Power",...
    "Laser Photo Diode","Brightness","Shutter","Gain","Deployment ID",...
    "Image Number","Number of Particles","Reserved for Future Use",...
    "Reserved for Future Use","Reserved for Future Use",...
    "Reserved for Future Use","Reserved for Future Use","Total Volume",...
    "Size Distribution"];                                                  % list of the variables names
variables(1,length(variables)+1:size(ALL,2))=NaN;                          % add NaN to the end of the list so that its size matches the number of columns of the csv
variables = array2table(variables);                                        % transform the array into a table for a concatenation later
variables = renamevars(variables,1:width(variables),...                    % change the variables'names for a concatenation later
    ALL.Properties.VariableNames);

units = ["N/A","N/A","N/A","N/A","N/A","N/A","Currently not available",... % list of the units of the variables
    "m","degree C","V","N/A","N/A","N/A","N/A","N/A","N/A","N/A","N/A",...
    "N/A","N/A","N/A","N/A","N/A","N/A","ul/l","ul/l"];
units(1,length(units)+1:size(ALL,2))=NaN;                                  % add NaN to the end of the list so that its size matches the number of columns of the csv
units = array2table(units);                                                % transform the array into a table for a concatenation later
units = renamevars(units,1:width(units),ALL.Properties.VariableNames);     % change the variables'names for a concatenation later


%% Addition of the titles to the top of the columns in the ALL table

ALL = [units; ALL];                                                        % add the units of the variables as an extra row at the top of the ALL table
ALL = [variables; ALL];                                                    % add the names of the variables as an extra row at the top of the ALL table
writetable(ALL,fullfile(location,file),"WriteVariableNames",false);        % overwrite the csv file selected by the user to save the changes made using this program

